version: "3"
services:
  app:
    restart: always
    build: ./api
    ports: 
      - "8080:8080"
    environment:
      - ML_APP_PORT=8080
      - MONGO_URI=mongodb://mongo:27017/ImageClassifierDB
  client:
    restart: always
    build: ./client
    ports: 
      - "3000:3000"
    environment:
      - REACT_APP_API_ADDR=http://127.0.0.1:8080
    stdin_open: true 
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports: # For Robo Mongo & not clashing with local mongo
      - "28018:27017"
