version: "3"
services:
  app:
    restart: always
    build: ./api
    ports: 
      - "8080:8080"
  client:
    restart: always
    build: ./client
    ports: 
      - "3000:3000"
    stdin_open: true 
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "28018:27017"
