apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: us.gcr.io/animal-classifier/api
        name: api
        resources: 
          requests:
            cpu: 400m
            memory: 1G
          limits:
            cpu: 400m
            memory: 1G
        ports:
        - containerPort: 8080
        env:
        - name: ML_APP_PORT
          value: "8080"
        - name: MONGO_URI
          value: "mongodb://mongo:27017/ImageClassifierDB"


---

apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  loadBalancerIP: "35.199.185.214"


  